apiVersion: v1
kind: Service
metadata:
  name: {{ include "desafio-app.fullname" . }}
  labels:
    desafio: experts
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    desafio: experts
