replicaCount: 2

image:
  repository: vitoriaortegaa/desafio-experts
  pullPolicy: IfNotPresent
  tag: "1.0.1"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: application-vitoria.local
      paths:
        - path: /
          pathType: Prefix
